library(shiny)
# library(shinythemes)
# library(shinyWidgets)
# library(colourpicker)
# library(DT)
# library(RColorBrewer)
# library(tidyverse)
# library(visNetwork)
# library(magrittr)
# library(cowplot)
# library(igraph)

shinyApp(ui = ui, server = server)