app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("test-visualize", screenshot = FALSE)

app$setInputs(elements_of_interest = "Ag",
              network_layout = "layout_with_sugiyama",
              go = "click", 
              wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(age_limit = c(3, 4),  wait_=FALSE, values_=FALSE)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(max_age_type = "Minimum",  wait_=FALSE, values_=FALSE)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(elements_of_interest = c("Ag", "As"),  wait_=FALSE, values_=FALSE)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(force_all_elements = TRUE,  wait_=FALSE, values_=FALSE)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(  wait_=FALSE, values_=FALSE)
app$snapshot(items = list(output = "networkplot"))



app$setInputs(force_all_elements = FALSE,
              elements_of_interest = "Ag", 
              max_age_type = "Maximum", wait_=FALSE, values_=FALSE)
app$setInputs(element_color = "#ED8AB1")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "network_degree_norm")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(elementpalette = "Purples")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "element_redox_network")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "element_hsab")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "pauling")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "num_localities")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "AtomicMass")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "NumberofProtons")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "TableGroup")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "TablePeriod")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "Density")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "SpecificHeat")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineral_color = "#25CF85")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_mineral_by = "max_age")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineralpalette = "PuOr")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_mineral_by = "num_localities")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_mineral_by = "mean_pauling")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_mineral_by = "cov_pauling")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_by_cluster = TRUE)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(cluster_algorithm = "Leading eigenvector")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_by_cluster = FALSE, highlight_element = TRUE)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(highlight_color = "#8AECFF")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(custom_selection_element = c("Au", "Bi"), allowInputNoBinding_ = TRUE)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(custom_selection_color = "#CF0048")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(element_label_size = 70)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(element_size_type = "network_degree_norm")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(element_size_scale = 50)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(element_size_type = "num_localities")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(element_size_type = "AtomicMass")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(element_size_type = "NumberofProtons")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(element_size_type = "Density")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(element_size_type = "SpecificHeat")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineral_size = 25)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineral_size_type = "max_age")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineral_size_scale = 15)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineral_size_type = "num_localities")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(element_label_color = "#332BD6")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineral_label_color = "#68A13D", mineral_label_size = 23)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineral_label_size = 0, element_shape = "ellipse")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(element_shape = "box")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(element_shape = "text")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineral_shape = "square")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineral_shape = "star")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineral_shape = "triangle")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(mineral_shape = "diamond")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(edge_color = "#992525")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_edge_by = "element_redox_network")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(edgepalette = "YlOrRd")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_edge_by = "element_redox_mineral")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_edge_by = "num_localities_mineral")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(edge_weight = 5)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(edge_weight = 2)
app$snapshot(items = list(output = "networkplot"))