app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("test-visualize-redox", screenshot = FALSE)

app$setInputs(elements_of_interest = "As",
              elements_by_redox = TRUE,
              network_layout = "layout_with_sugiyama",
              go = "click", 
              age_limit = c(3,4),
              wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(element_color = "#ED8AB1")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "network_degree_norm")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(elementpalette = "Purples")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "element_redox_network")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "element_hsab")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "pauling")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "num_localities")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "AtomicMass")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "NumberofProtons")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "TableGroup")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "TablePeriod")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "Density")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_element_by = "SpecificHeat")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_by_cluster = TRUE)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(color_by_cluster = FALSE, highlight_element = TRUE)
app$snapshot(items = list(output = "networkplot"))
app$setInputs(highlight_color = "#8AECFF")
app$snapshot(items = list(output = "networkplot"))
app$setInputs(custom_selection_color = "#CF0048")
app$snapshot(items = list(output = "networkplot"))